spring.application.name=professional-portfolio-api
spring.datasource.url=jdbc:postgresql://localhost:5432/db_professional_portfolio
spring.datasource.username=postgres
spring.datasource.password=aeAJXsNc8KCojtDFhxJU7YnWJiY2WcQP0nc5aTwMuno7
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect